[project]
name = "django-tree-comments"
version = "0.0.4"
description = "A django library for building comments in tree structure."
authors = [{ name = "jukanntenn", email = "jukanntenn@outlook.com" }]
requires-python = ">=3.7,<4.0"
readme = "README.md"
license = "BSD-3-Clause"
keywords = ["django"]
dependencies = ["django-cte>=1.3.3", "django-tree-queries>=0.7.0,<0.8"]

[project.urls]
Repository = "https://github.com/jukanntenn/django-tree-comments"

[dependency-groups]
dev = ["pytest>=6.2.5,<7", "pytest-django>=4.5.2,<5"]
lint = ["djlint>=1.7.4"]

[tool.hatch.build.targets.sdist]
include = ["tree_comments"]

[tool.hatch.build.targets.wheel]
include = ["tree_comments"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
python_files = "tests.py test_*.py"

[tool.uv.workspace]
exclude = ["examples/default", "examples/custom"]

[tool.ruff]
exclude = ["**/migrations/"]
