[tox]
envlist =
    py310-django52
    py311-django52
    py312-django52
    py313-django52
    py314-django52
minversion = 4.0

[testenv]
runner = uv-venv-lock-runner
deps = Django>=5.2,<6.0
setenv =
    PYTHONWARNINGS = default
    DJANGO_SETTINGS_MODULE = tests.settings
commands =
    pytest {posargs}

[testenv:coverage]
runner = uv-venv-lock-runner
commands =
    pytest --cov=tree_comments --cov-report=term-missing --cov-report=xml

[gh]
python_versions =
    3.10=py310
    3.11=py311
    3.12=py312
    3.13=py313
    3.14=py314
