[tox]
envlist =
    py38-django{42,50,51}
    py39-django{42,50,51}
    py310-django{42,50,51,main}
    py311-django{42,50,51,main}
    py312-django{42,50,51,main}
minversion = 4.0

[testenv]
runner = uv-venv-lock-runner
deps =
    django42: Django>=4.2,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django-main: https://github.com/django/django/archive/main.tar.gz
setenv =
    PYTHONWARNINGS = default
    DJANGO_SETTINGS_MODULE = tests.settings
commands =
    pytest {posargs}

[testenv:coverage]
runner = uv-venv-lock-runner
commands =
    pytest --cov=tree_comments --cov-report=term-missing --cov-report=xml

[gh]
python_versions =
    3.8=py38
    3.9=py39
    3.10=py310
    3.11=py311
    3.12=py312
