"""report.md generator (LLM-readable).

Structure (finalized in design.md):
  1. Context block: red-flag definitions + CTE SQL semantics + schema notes ->
     the LLM can diagnose without reading the code
  2. Per-scenario section: parameters -> timing -> query -> red flags (highlighted) -> PG extras -> diagnostic hints
  3. Cross-scenario summary: cross-scenario comparison (same shape across scales, same scale across backends)
  4. Empty optimization decision-table skeleton

Timing unit: pytest-benchmark stats are in seconds (default time.perf_counter); the report
converts them to milliseconds (ms).
"""

from __future__ import annotations

# Context block: a fixed diagnostic context. With this md, the LLM can understand the system
# without looking at the codebase.
CONTEXT_BLOCK = """# Context (must-read before diagnosis)

This report is auto-generated by the performance harness to analyze the CTE tree-comment
query performance of django-tree-comments. You (the LLM) will diagnose performance
bottlenecks and propose optimizations based on this report. Below is all the context
needed to understand it.

## System under test

django-tree-comments: a Django tree-comment app. Comments are modeled with an
**adjacency list** (each comment records parent_id), and fetching the whole tree uses a
**recursive CTE** (WITH RECURSIVE), generated by the django-cte library.

### Real SQL semantics of the CTE query (threaded_for_instance)

```sql
WITH RECURSIVE cte AS (
    -- Anchor: visible root comments under the object (is_public=TRUE AND is_removed=FALSE)
    SELECT ...all columns..., id AS root_id, 0 AS depth
    FROM tree_comments_comment
    WHERE content_type_id=? AND object_pk=?
      AND is_public AND NOT is_removed AND parent_id IS NULL
    UNION ALL
    -- Recursive branch: drills down along parent_id (NOTE: the recursive branch does NOT apply a visible filter)
    SELECT ...all columns..., cte.root_id, cte.depth+1
    FROM tree_comments_comment
    INNER JOIN cte ON parent_id = cte.id
)
SELECT ...all columns..., cte.root_id, cte.depth
FROM tree_comments_comment
INNER JOIN cte ON id = cte.id
ORDER BY root_id DESC, submit_date ASC, id ASC;   -- NOTE: the depth annotation is computed but not used for sorting
```

### Known design characteristics (not bugs; facts to consider during analysis)

1. **parent_id has no index on PG/SQLite** (an FK does not auto-create an index); MySQL InnoDB auto-creates one.
2. **No (content_type, object_pk) composite index**; only a single-column object_pk index exists.
3. **The recursive branch does not filter visibility**: when an intermediate node is is_removed, its subtree is still fetched.
4. **Sorting is a flat time order** (not a hierarchical indented order); the depth annotation does not participate in sorting.
5. **bulk_create does not call save()**, and submit_date is auto-populated in save() -> batch inserts must set it explicitly.

## Red-flag definitions (five performance signals)

| Type | Meaning | Trigger criteria |
|------|------|---------|
| `seq_scan_large_table` | Full table scan on a large table (should have used an index but did not) | PG: Seq Scan + Actual Rows>1000; MySQL: type=ALL + rows>1000; SQLite: starts with SCAN and no USING |
| `estimation_off` | Severe row-count estimation deviation (optimizer picked the wrong strategy) | PG: \\|Plan Rows-Actual Rows\\|/Actual Rows>0.5; MySQL/SQLite: not applicable |
| `spilled_to_disk` | Sort/intermediate result spilled to disk (hidden slowdown) | PG: external merge/Disk/Temp Blocks; MySQL: Using filesort; SQLite: USE TEMP B-TREE |
| `recursive_bulk` | Large recursive intermediate result (fanout amplification) | PG: Recursive Union loops>10 or WorkTable rows>1000; MySQL: Materialize CTE loops/rows; SQLite: presence of RECURSIVE STEP |
| `slow_node` | Abnormally slow execution-plan node (captures hidden slow nodes) | PG: Actual Total Time>1000ms (at most 5 reported, sorted by elapsed time desc); MySQL/SQLite: not applicable |

## SQLite diagnostic limitations

Because CPython does not expose the sqlite3* C handle (ctypes access causes a segfault),
SQLite cannot collect db_status cache-hit ratio or spill byte counts. SQLite diagnostic
depth is lower than PG/MySQL, but EXPLAIN + red flags remain effective.

## Metric units

- Timing: milliseconds (ms). From pytest-benchmark warm multi-round measurements (the default
  timer is time.perf_counter, returning seconds; already converted to ms).
- Memory: KB (tracemalloc peak; Python-object memory; excludes DB-process memory).
- Buffer hit ratio: percentage (PG only).

---

"""


def _fmt_ms(sec_value: float | None) -> str:
    """Seconds to milliseconds for display. None shows '-'."""
    if sec_value is None:
        return "-"
    return f"{sec_value * 1000:.2f}"


def _fmt_kb(bytes_value: float | None) -> str:
    """Bytes to KB."""
    if bytes_value is None:
        return "-"
    return f"{bytes_value / 1024:.0f}"


def _render_scenario_section(metrics: dict) -> str:
    """Render the section for a single scenario."""
    sid = metrics.get("benchmark_id", "?")
    scenario = metrics.get("scenario", {})
    db = metrics.get("db", {})
    timing = metrics.get("timing", {})
    query = metrics.get("query", {})
    plan = metrics.get("plan", {})
    red_flags = plan.get("red_flags", {})
    pg_extras = metrics.get("postgres_extras", {})
    resources = metrics.get("resources", {})

    lines = []
    lines.append(f"## Scenario: {sid}")
    lines.append("")
    lines.append("**Parameters**:")
    lines.append(
        f"- shape={scenario.get('tree_shape')} scale={scenario.get('scale')} "
        f"depth={scenario.get('depth')} fanout={scenario.get('fanout')} "
        f"nodes={scenario.get('total_nodes')} kind={scenario.get('kind')}"
    )
    lines.append(f"- backend={db.get('backend')} version={db.get('version', '')[:50]}")
    lines.append("")

    lines.append("**Timing** (ms, warm multi-round):")
    lines.append(
        f"- median={_fmt_ms(timing.get('median'))}  p95={_fmt_ms(timing.get('p95'))}  "
        f"min={_fmt_ms(timing.get('min'))}  max={_fmt_ms(timing.get('max')) if timing.get('max') else '-'}  "
        f"rounds={timing.get('rounds', '-')}"
    )
    lines.append("")

    lines.append("**Queries**:")
    lines.append(
        f"- total_queries={query.get('total_queries')}  distinct_templates={query.get('distinct_templates')}  "
        f"n_plus_one_suspected={query.get('n_plus_one_suspected')}  most_repeated={query.get('most_repeated_count')}"
    )
    lines.append("")

    rf_count = red_flags.get("count", 0)
    if rf_count == 0:
        lines.append("**Red flags**: none ✅")
    else:
        lines.append(f"**Red flags** ({rf_count}):")
        for f in red_flags.get("flags", []):
            severity = f.get("severity", "warning")
            icon = "🔴" if severity == "warning" else "🟡"
            lines.append(f"- {icon} `{f.get('type')}`: {f.get('detail')}")
    lines.append("")

    if pg_extras:
        lines.append("**PG depth metrics**:")
        ri = pg_extras.get("recursion_iterations")
        hit = pg_extras.get("shared_buffers_hit_pct")
        if ri is not None:
            lines.append(f"- recursive_iterations={ri}")
        if hit is not None:
            lines.append(f"- buffer_hit_ratio={hit}%")
        lines.append("")

    peak_kb = resources.get("peak_kb") or (
        resources.get("peak_bytes", 0) / 1024 if resources.get("peak_bytes") else None
    )
    lines.append(f"**Peak memory**: {_fmt_kb(resources.get('peak_bytes') or (peak_kb * 1024 if peak_kb else 0))} KB")
    lines.append("")

    return "\n".join(lines)


def _render_cross_scenario_summary(metrics_list: list[dict]) -> str:
    """Render cross-scenario comparison tables: same shape across scales, same scale across backends."""
    if not metrics_list:
        return ""

    lines = ["## Cross-scenario summary", ""]

    # Group by (shape, backend) to observe scaling growth
    lines.append("### Same shape and backend, scaling growth (median, ms)")
    lines.append("")
    lines.append("| Shape | Backend | 1k | 5k | 10k |")
    lines.append("|------|------|----|----|-----|")
    # Organize the data
    grouped = {}
    for m in metrics_list:
        sc = m.get("scenario", {})
        key = (sc.get("tree_shape"), m.get("db", {}).get("backend"))
        scale = sc.get("scale")
        median = m.get("timing", {}).get("median")
        grouped.setdefault(key, {})[scale] = median

    for (shape, backend), scales in sorted(grouped.items()):
        row = f"| {shape} | {backend} "
        for s in (1000, 5000, 10000):
            v = scales.get(s)
            row += f"| {_fmt_ms(v)} "
        row += "|"
        lines.append(row)
    lines.append("")

    # Same scale and shape, cross-backend comparison
    lines.append("### Same scale and shape, cross-backend comparison (median, ms)")
    lines.append("")
    lines.append("| Shape | Scale | sqlite | postgres | mysql |")
    lines.append("|------|------|--------|----------|-------|")
    grouped2 = {}
    for m in metrics_list:
        sc = m.get("scenario", {})
        key = (sc.get("tree_shape"), sc.get("scale"))
        backend = m.get("db", {}).get("backend")
        median = m.get("timing", {}).get("median")
        grouped2.setdefault(key, {})[backend] = median

    for (shape, scale), by_backend in sorted(grouped2.items()):
        row = f"| {shape} | {scale} "
        for b in ("sqlite", "postgres", "mysql"):
            v = by_backend.get(b)
            row += f"| {_fmt_ms(v)} "
        row += "|"
        lines.append(row)
    lines.append("")

    # Red-flag totals comparison
    lines.append("### Red-flag totals per scenario")
    lines.append("")
    lines.append("| Scenario | Red flags | Red-flag types |")
    lines.append("|------|--------|---------|")
    for m in metrics_list:
        rf = m.get("plan", {}).get("red_flags", {})
        types = ", ".join(sorted(set(rf.get("types", []))))
        lines.append(f"| {m.get('benchmark_id')} | {rf.get('count', 0)} | {types} |")
    lines.append("")

    return "\n".join(lines)


def _render_decision_table() -> str:
    """Render the empty optimization decision-table skeleton."""
    return """## Optimization decision table (to be filled in by LLM analysis)

Based on the red flags and cross-scenario comparison above, pinpoint the bottlenecks and
propose optimization hypotheses. Each optimization must specify a verification scenario.

| # | Bottleneck | Current metric | Optimization hypothesis | Expected gain | Verification scenario | Status |
|---|--------|---------|---------|---------|---------|------|
| 1 | (to fill) | | | | | pending |
| 2 | (to fill) | | | | | pending |
| 3 | (to fill) | | | | | pending |

"""


def write_markdown_report(metrics_list: list[dict], output_path: str) -> None:
    """Generate the complete report.md.

    Args:
        metrics_list: list of dicts returned by collect_scenario_metrics
        output_path: output .md file path
    """
    lines = []
    lines.append(CONTEXT_BLOCK)

    # Meta info
    if metrics_list:
        first = metrics_list[0]
        lines.append(f"**Generated at**: {first.get('timestamp', '-')}  ")
        lines.append(f"**Git commit**: {first.get('git_commit', '-')}  ")
        lines.append(f"**Scenario count**: {len(metrics_list)}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Per-scenario sections
    lines.append("# Per-scenario details")
    lines.append("")
    for m in metrics_list:
        lines.append(_render_scenario_section(m))
        lines.append("---")
        lines.append("")

    # Cross-scenario comparison
    lines.append(_render_cross_scenario_summary(metrics_list))

    # Decision table
    lines.append(_render_decision_table())

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
