"""Theme-based sentence pools for generating realistic demo comments.

Each theme has three lists:
- ``roots``:    sentences opening a topic (used for root comments).
- ``replies``:  neutral continuing sentences (used for normal replies).
- ``followups``: rebuttal / supplement / follow-up tone (used for deep chains).
"""

SENTENCES = {
    "announcement": {
        "roots": [
            "Finally a clean threaded-comments package for Django, this is exactly what I was missing.",
            "Congrats on the release! The recursive CTE approach is the right call.",
            "Bookmarked. Going to migrate our old django-contrib-comments fork this weekend.",
            "The swap model via TREE_COMMENTS_COMMENT_MODEL is a nice touch.",
            "Does this handle soft-delete with the [deleted] placeholder like Reddit?",
            "Excited to try the HTMX integration shown in the demo.",
            "Appreciate that it stays dependency-light beyond django-cte.",
            "Will there be a typed-frontend example next?",
            "The depth/root_id annotation trick is clever, I'd never seen it done that way.",
            "Quick question: does it work on MySQL 8 or only Postgres?",
            "Loving the minimal template override surface, easy to theme.",
            "Tested on SQLite first, blazing fast for local dev.",
            "Good move shipping a seed command instead of a fixture dump.",
            "Any plan for pagination of long threads?",
            "The moderation flags feel familiar, nice for parity with the old framework.",
            "Could the reply URL accept a next param for SPA flows?",
            "Impressed by how little boilerplate is needed to wire it up.",
            "Does the CTE play nicely with pg materialized views?",
            "Comment sections are finally pleasant to build again.",
            "Will the dark-mode CSS ship inside the package or stay demo-only?",
            "Just confirmed it works on Django 4.2 LTS, no issues.",
            "The honeypot field is a thoughtful default.",
            "Glad security_hash uses salted_hmac and not a plain hash.",
            "Curious if there's a DRF serializer example coming.",
            "This fills a real gap between flat comments and a full forum.",
            "Nice that object_pk is a string, makes polymorphic targets easy.",
            "Counting this as the new default for any greenfield Django site.",
            "The for_model manager method is handy for dashboards.",
            "Hope the docs cover customizing the form target next.",
            "Solid 0.0.4 release, looking forward to 0.1.",
        ],
        "replies": [
            "Same here, dropped our hand-rolled nesting right away.",
            "Confirmed on Postgres 16, the CTE plan looks clean.",
            "Works on MySQL 8.0 too, no surprises.",
            "The soft-delete keeps is_removed rows for threading integrity.",
            "Pagination isn't built in, but easy to add with window functions.",
            "HTMX makes the threaded UI almost trivial.",
            "django-cte is the only real dependency, very lean.",
            "The depth annotation is computed in SQL, no extra queries.",
            "You can override almost everything via template paths.",
            "Security hash validates timestamp within a 2h window by default.",
            "Migrating from contrib-comments took about an afternoon.",
            "The reply endpoint returns a ready-to-render form fragment.",
            "I pinned django-cte>=1.3.3 without issues.",
            "The example project is the fastest way to grok it.",
            "object_pk being a string handles UUID and composite keys too.",
            "No DRF example yet, but the JSON form endpoint is a start.",
            "You can swap the form class with TREE_COMMENTS_COMMENT_FORM.",
            "The can_moderate permission integrates with the admin.",
            "Site FK is used to scope comments, set SITE_ID carefully.",
            "Empty-state copy is just a template override.",
            "Works on SQLite 3.50 in our CI.",
            "The seed command is idempotent if you keep the same titles.",
            "Reply forms post to the same post endpoint with parent set.",
            "Ordering uses (-root_id, submit_date, id) for stable layout.",
            "Bulk create is batched in the perf harness, not the demo.",
            "The honeypot field is hidden via a template attribute.",
            "Use Comment.get_reply_url() to link the reply button.",
            "Threading is materialized at query time, not on save.",
            "Custom models just subclass AbstractComment.",
            "Glad it supports both anonymous and authenticated commenters.",
        ],
    },
    "ama": {
        "roots": [
            "What made you choose a recursive CTE over adjacency-list traversal in Python?",
            "How does it behave under heavy write contention on the comments table?",
            "Is there a recommended way to denormalize reply counts?",
            "What's the realistic max depth you'd recommend before paginating?",
            "Any gotchas with read replicas and the CTE query?",
            "How would you integrate this with a React frontend?",
            "Does the moderation queue scale to thousands of pending comments?",
            "Why object_pk as a string instead of a typed FK?",
            "How do you handle comment edits vs soft deletes?",
            "What's the overhead of the depth annotation on large threads?",
            "Any plan to support nested-set or materialized path as an alternative?",
            "How does it interact with Django's atomic blocks?",
            "What's your take on realtime updates via websockets?",
            "Is the security_hash replayable across users?",
            "How would you shard comments across databases?",
            "Do you benchmark against django-mptt or django-treebeard?",
            "What pattern do you recommend for email notifications on reply?",
            "How do you prevent the typical N+1 on rendering a deep tree?",
            "Is there a story for threaded comments on multiple content types?",
            "What's the migration path from django-threadedcomments?",
            "How do you test the CTE across database backends?",
            "Any guidance on caching the threaded query result?",
            "What happens if a parent comment is hard-deleted out of band?",
            "How do you rate-limit anonymous comment submissions?",
            "Is there a reference deployment at scale?",
            "How does the honeypot interact with screen readers?",
            "What's the recommended CSRF setup for the HTMX flow?",
            "Do you support markdown rendering of comment bodies?",
            "How would you add per-user mention notifications?",
            "What's the long-term plan for the 1.0 API surface?",
        ],
        "replies": [
            "Great question, I had the same one last week.",
            "Short answer: the CTE keeps it to a single round-trip.",
            "We benchmarked it; depth annotation overhead is under 5%.",
            "Denormalized counts work fine via a post_save signal.",
            "Read replicas are fine since threading is read-only.",
            "For React, the JSON form endpoint is your friend.",
            "Moderation queue is paginated via in_moderation().",
            "object_pk as string keeps it generic across PK types.",
            "Edits aren't modeled; we recommend append-only corrections.",
            "Hard-delete of a parent orphans children; use soft-delete.",
            "Adjacency list + CTE beats nested-set for write-heavy loads.",
            "Atomic blocks work normally; no special handling needed.",
            "Websockets are out of scope; pair with channels separately.",
            "security_hash binds the timestamp, so replays expire in 2h.",
            "Sharding by content_type works reasonably well.",
            "We don't benchmark against mptt; different data model.",
            "Email-on-reply is a 20-line signal receiver.",
            "select_related on parent/user avoids N+1 at render.",
            "Multiple content types are the whole point of generic FKs.",
            "Migration from threadedcomments is mostly data reshuffling.",
            "We run the CTE test suite on PG, MySQL, and SQLite.",
            "Cache with a versioned key bumped on new comment.",
            "Soft-delete keeps children intact and visible.",
            "Rate-limit via django-ratelimit on the post view.",
            "No public scale deployment yet, but the harness is open.",
            "Honeypot is hidden and aria-hidden for accessibility.",
            "Standard Django CSRF works; HTMX forwards the cookie.",
            "Markdown is a template-side concern; bodies are plain text.",
            "Mentions need a custom signal; not built in.",
            "1.0 will lock the manager and template contract.",
            "We pin django-cte because the API is still moving.",
            "Hope that helps, happy to dig deeper.",
            "Worth a dedicated doc page, agreed.",
            "Will add an example for that next release.",
            "Confirmed by our internal load test.",
            "Good point, I'll open an issue.",
            "Marking this as a known limitation for now.",
            "Reach out if you want to pair on it.",
            "The README has a one-line summary.",
            "Docs PRs welcome.",
        ],
    },
    "technical": {
        "roots": [
            "The recursive CTE anchors on visible roots and recurses via parent=cte.col.id.",
            "depth and root_id are annotations, not columns; they only exist on the CTE queryset.",
            "threaded_for_instance orders by (-root_id, submit_date, id) to keep subtrees contiguous.",
            "The base case annotates root_id=F('id') and depth=Value(0).",
            "The recursive case annotates depth=cte.col.depth + Value(1).",
            "union(all=True) merges the base and recursive arms.",
            "select_related('parent','user','content_type') avoids follow-up queries at render.",
            "visible() filters is_public=True and is_removed=False.",
            "roots() is visible().filter(parent__isnull=True).",
            "cte_for_instance scopes by content_type and object_pk via for_model().",
            "The manager is built via models.Manager.from_queryset(CommentQuerySet).",
            "Comment.save auto-fills submit_date if it's None.",
            "CommentForm adds a honeypot field on top of CommentDetailsForm.",
            "clean_parent validates the parent pk exists in the comment table.",
            "get_comment_create_data assembles the dict for CommentModel(**data).",
            "check_for_duplicate_comment matches on name/email/url and same-day submit.",
            "security_hash is salted_hmac over content_type-object_pk-timestamp.",
            "timestamp validation rejects submissions older than COMMENTS_TIMEOUT (2h).",
            "ReplyView.get resolves content_type+object_pk from the query string.",
            "CommentPostView.form_valid renders comment.html with the new object on ?format=html.",
            "CommentPostView.form_invalid re-renders form.html with errors on ?format=html.",
            "Both success and failure return HTTP 200 text/html; the client distinguishes by body.",
            "create_comment does not re-query via the CTE; self.object is the raw saved instance.",
            "Templates resolve via tree_comments/<app>/<model>/<name>.html then app-level then default.",
            "render_comment_app calls threaded_for_instance(obj) and renders app.html.",
            "get_comment_model reads TREE_COMMENTS_COMMENT_MODEL with a 'tree_comments.Comment' default.",
            "Swappable Meta ties Comment to the TREE_COMMENTS_COMMENT_MODEL setting.",
            "CommentFlag uses SUGGEST_REMOVAL / MODERATOR_DELETION / MODERATOR_APPROVAL constants.",
            "in_moderation() returns is_public=False and is_removed=False rows.",
            "The Site FK scopes comments to the current SITE_ID.",
        ],
        "replies": [
            "Right, the anchor is just visible roots, which keeps the recursion bounded.",
            "And depth being an annotation means bare .get() won't have it.",
            "That ordering invariant is what makes client-side insertion feasible.",
            "Note Value(0) needs output_field=IntegerField() for correct typing.",
            "Same for the +Value(1) increment in the recursive arm.",
            "union(all=True) preserves duplicates, which matters for sibling roots.",
            "select_related is safe because parent/user are single-valued.",
            "visible() is the canonical read filter; compose everything on top of it.",
            "roots() is the base of the recursion, so it must already be visible.",
            "for_model accepts either a class or an instance for scoping.",
            "from_queryset is what exposes queryset methods on the manager.",
            "That submit_date fallback is handy for raw creates in tests.",
            "Honeypot is the only thing CommentForm adds over CommentDetailsForm.",
            "Without clean_parent, stale parent pks would 500 on save.",
            "data dict keys must match model field names exactly.",
            "Duplicate detection is intentionally lax to avoid surprising users.",
            "salted_hmac uses the SECRET_KEY, so rotating it invalidates pending forms.",
            "2h is generous for typing a comment but tight enough to deter replays.",
            "ReplyView reuses CommentForm with parent= pre-filled.",
            "That's why comment.html must key child-detection off parent_id, not depth.",
            "Form-error re-render keeps the user's typed content in place.",
            "200-for-everything is unusual but lets HTMX swap without status checks.",
            "Exactly; the new object has no depth/root_id until re-queried.",
            "The three-tier lookup is the standard Django override idiom.",
            "render_comment_app is the single entry point for the full threaded UI.",
            "Defaults keep zero-config usable; settings unlock customization.",
            "Swappable Meta is what makes the custom example work.",
            "Flags are intentionally minimal; full moderation is app-level.",
            "in_moderation is the queue backing the admin list.",
            "Multi-site setups rely on that FK; don't drop it.",
        ],
    },
    "debate": {
        "roots": [
            "I'd argue the adjacency-list model is actually simpler than a CTE for small trees.",
            "Has anyone benchmarked this against a materialized path on write-heavy workloads?",
            "I'm skeptical that single-query threading holds up past 10k comments.",
        ],
        "replies": [
            "That's fair for small trees, but the CTE keeps reads constant-time regardless of size.",
            "Materialized path writes are O(depth) on every insert; adjacency is O(1).",
            "The 10k claim is validated in the perf harness; the plan stays index-driven.",
            "Simplicity and performance pull in opposite directions here.",
            "Write-heavy workloads care about insert cost, not read fan-out.",
            "10k is where you'd want pagination regardless of the traversal strategy.",
            "I concede the CTE SQL is harder to read than a Python traversal.",
            "But read amplification on adjacency-with-Python is the real killer.",
            "Agreed pagination is orthogonal; the CTE just defers the need for it.",
            "Counterpoint: most apps never hit 10k comments on a single target.",
            "True, but designing for the tail keeps the API stable later.",
            "Materialized path also needs a re-write on parent reparenting.",
            "Which adjacency handles for free, I'll grant you that.",
            "So the tradeoff is insert simplicity vs read throughput.",
            "Exactly, and this package optimizes for read throughput.",
            "For write-heavy forums, nested-set might still win.",
            "Nested-set writes are O(n) though, which scales poorly.",
            "Right, no silver bullet; pick the model for your workload.",
            "I think the CTE is a reasonable default for content-comment use cases.",
            "And it's swappable if you disagree, which I appreciate.",
        ],
        "followups": [
            "Hold on, O(1) inserts assume no re-balancing.",
            "Even so, the read path is what users feel, not the insert latency.",
            "Re-balancing is the hidden cost of nested-set, often ignored.",
            "Agreed, but read latency only matters if you render synchronously.",
            "Async rendering flips the tradeoff back toward adjacency.",
            "True; for SSR sites the CTE still wins.",
            "Unless you cache aggressively, then adjacency becomes viable again.",
            "Caching invalidation on threaded data is notoriously painful though.",
            "Fair; cache by root_id and invalidate the whole subtree on write.",
            "Which is exactly what root_id annotation enables here.",
            "That's actually a strong argument for keeping root_id denormalized.",
            "And the CTE computes it on the fly, no schema cost.",
            "Conceded; the design is more cohesive than I first thought.",
            "The remaining concern is portability across DBs.",
            "Addressed: PG, MySQL 8, and SQLite 3.50 are all tested.",
            "MySQL 8 needs the CTE enabled, but that's the default now.",
            "And SQLite's CTE planner has improved a lot recently.",
            "Alright, I'm convinced this is the right default.",
            "Glad we talked it through; the docs should capture this nuance.",
            "I'll open a PR adding a tradeoffs section.",
        ],
    },
}
